import type { Metadata } from "next";
import { Inter, Poppins, Montserrat, PT_Serif } from 'next/font/google'
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const inter = Inter({
  weight: ['400', '700'], 
  subsets: ['latin'],
  variable: '--font-inter',
});

const montserrat = Montserrat({
  weight: ['400','500', '600', '700', ],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-montserrat',
  
})

const poppins = Poppins({
  weight: ['400','500', '600', '700' ],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

const ptSerif = PT_Serif({
  weight: ['400', '700'], 
  subsets: ['latin'],
  variable: '--font-pt-serif',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} ${ptSerif.variable} ${montserrat.variable}`}>
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
